import { AlignCenter, AlignLeft, AlignRight, ChevronsUpDown, Copy, Link2, Maximize2, Paintbrush, SlidersHorizontal, Trash2, Type } from 'lucide-react';
import { useState } from 'react';
import { useEditorStore } from '../stores/editorStore';
import { analyzeResponsiveness, applySafeResponsiveFixes, ensureAnimationStyles, setDeviceVisibility } from '../utils/responsive';
import { getActivePage } from '../stores/editorStore';

export function Inspector() {
  const selected = useEditorStore((state)=>state.selected);
  const tab = useEditorStore((state)=>state.inspectorTab);
  const setTab = useEditorStore((state)=>state.setInspectorTab);
  const project = useEditorStore((state)=>state.project);
  const updatePage = useEditorStore((state)=>state.updatePage);
  const page=getActivePage(project);
  const issues=analyzeResponsiveness(page.html,page.css);
  function send(type:string,payload:Record<string,string>={}) { const frame=document.querySelector<HTMLIFrameElement>('.canvas-frame iframe');frame?.contentWindow?.postMessage({source:'webdev-editor',type,id:selected?.id,...payload},'*') }
  return <aside className="inspector"><div className="inspector-tabs"><button className={tab==='content'?'active':''} onClick={()=>setTab('content')}>Conteúdo</button><button className={tab==='style'?'active':''} onClick={()=>setTab('style')}>Estilo</button><button className={tab==='advanced'?'active':''} onClick={()=>setTab('advanced')}>Avançado</button></div>
    {!selected ? <div className="no-selection"><SlidersHorizontal/><h3>Nenhum elemento selecionado</h3><p>Clique elemento no canvas.</p>{issues.length?<div className="responsive-audit"><strong>{issues.length} ajustes responsivos</strong>{issues.slice(0,3).map(issue=><span key={issue.type+issue.message}>{issue.message}</span>)}<button onClick={()=>updatePage({css:applySafeResponsiveFixes(page.css)},'Corrigir responsividade')}>Aplicar correções seguras</button></div>:null}</div> : <div className="inspector-content"><div className="selected-heading"><span>&lt;{selected.tagName}&gt;</span><strong>{selected.className||selected.tagName}</strong></div>
    {tab==='content'?<ContentControls selected={selected} send={send}/>:null}{tab==='style'?<StyleControls selected={selected} send={send}/>:null}{tab==='advanced'?<AdvancedControls selected={selected} send={send} pageCss={page.css} updateCss={css=>updatePage({css},'Configurar elemento')} breakpoints={project.settings.breakpoints}/>:null}</div>}
  </aside>;
}

type Send=(type:string,payload?:Record<string,string>)=>void;
function ContentControls({selected,send}:{selected:NonNullable<ReturnType<typeof useEditorStore.getState>['selected']>;send:Send}) {
  return <><ControlSection title="Conteúdo" icon={<Type/>}>{selected.text!==''?<label className="field vertical"><span>Texto</span><textarea defaultValue={selected.text} onBlur={e=>send('content',{property:'text',value:e.target.value})}/></label>:null}<label className="field vertical"><span>Classes CSS</span><input defaultValue={selected.className} onBlur={e=>send('content',{property:'className',value:e.target.value})}/></label>{selected.tagName==='a'?<label className="field vertical"><span>Link</span><input placeholder="https://" onBlur={e=>send('content',{property:'href',value:e.target.value})}/></label>:null}</ControlSection></>;
}
function StyleControls({selected,send}:{selected:NonNullable<ReturnType<typeof useEditorStore.getState>['selected']>;send:Send}) {
  const s=selected.styles;
  const value=(key:string)=>s[key]??'';
  return <><ControlSection title="Layout" icon={<Maximize2/>}><div className="two-fields"><Field label="Largura" value={value('width')} onChange={v=>send('style',{property:'width',value:v})}/><Field label="Altura" value={value('height')} onChange={v=>send('style',{property:'height',value:v})}/></div><label className="field vertical"><span>Exibição</span><select defaultValue={value('display')} onChange={e=>send('style',{property:'display',value:e.target.value})}><option>block</option><option>flex</option><option>grid</option><option>inline-flex</option><option>none</option></select></label><div className="alignment"><span>Alinhamento</span><button onClick={()=>send('style',{property:'textAlign',value:'left'})}><AlignLeft/></button><button onClick={()=>send('style',{property:'textAlign',value:'center'})}><AlignCenter/></button><button onClick={()=>send('style',{property:'textAlign',value:'right'})}><AlignRight/></button></div><Field label="Margem" value={value('margin')} onChange={v=>send('style',{property:'margin',value:v})}/><Field label="Preenchimento" value={value('padding')} onChange={v=>send('style',{property:'padding',value:v})}/></ControlSection>
  <ControlSection title="Tipografia" icon={<Type/>}><div className="two-fields"><Field label="Tamanho" value={value('fontSize')} onChange={v=>send('style',{property:'fontSize',value:v})}/><Field label="Peso" value={value('fontWeight')} onChange={v=>send('style',{property:'fontWeight',value:v})}/></div><label className="color-field"><span>Cor</span><input type="color" defaultValue={toHex(value('color'))} onChange={e=>send('style',{property:'color',value:e.target.value})}/><code>{toHex(value('color'))}</code></label></ControlSection>
  <ControlSection title="Aparência" icon={<Paintbrush/>}><label className="color-field"><span>Fundo</span><input type="color" defaultValue={toHex(value('backgroundColor'))} onChange={e=>send('style',{property:'backgroundColor',value:e.target.value})}/><code>{toHex(value('backgroundColor'))}</code></label><Field label="Borda" value={value('border')||'0 solid transparent'} onChange={v=>send('style',{property:'border',value:v})}/><Field label="Arredondamento" value={value('borderRadius')} onChange={v=>send('style',{property:'borderRadius',value:v})}/><Field label="Sombra" value={value('boxShadow')||'none'} onChange={v=>send('style',{property:'boxShadow',value:v})}/><Field label="Opacidade" value={value('opacity')||'1'} onChange={v=>send('style',{property:'opacity',value:v})}/></ControlSection>
  <ControlSection title="Posicionamento" icon={<Maximize2/>}><label className="field vertical"><span>Posição</span><select defaultValue={value('position')||'static'} onChange={e=>send('style',{property:'position',value:e.target.value})}><option>static</option><option>relative</option><option>absolute</option><option>fixed</option><option>sticky</option></select></label><div className="two-fields"><Field label="Camada Z" value={value('zIndex')||'auto'} onChange={v=>send('style',{property:'zIndex',value:v})}/><Field label="Overflow" value={value('overflow')||'visible'} onChange={v=>send('style',{property:'overflow',value:v})}/></div></ControlSection></>;
}
function AdvancedControls({selected,send,pageCss,updateCss,breakpoints}:{selected:NonNullable<ReturnType<typeof useEditorStore.getState>['selected']>;send:Send;pageCss:string;updateCss:(css:string)=>void;breakpoints:{mobile:number;tablet:number;desktop:number}}) {
  const [confirm,setConfirm]=useState(false);
  function animation(value:string){if(!value){send('style',{property:'animation',value:''});return}updateCss(ensureAnimationStyles(pageCss));send('style',{property:'animation',value:`${value} .65s ease both`})}
  function visibility(device:'desktop'|'tablet'|'mobile',hidden:boolean){updateCss(setDeviceVisibility(pageCss,selected.id,device,hidden,breakpoints))}
  return <><ControlSection title="Identidade" icon={<Link2/>}><label className="field vertical"><span>ID editorial</span><input value={selected.id} readOnly/></label><label className="field vertical"><span>Classe CSS</span><input defaultValue={selected.className} onBlur={e=>send('content',{property:'className',value:e.target.value})}/></label></ControlSection><ControlSection title="Movimento" icon={<ChevronsUpDown/>}><label className="field vertical"><span>Animação de entrada</span><select defaultValue="" onChange={e=>animation(e.target.value)}><option value="">Nenhuma</option><option value="wdFadeUp">Surgir para cima</option><option value="wdFadeIn">Aparecer</option><option value="wdZoomIn">Ampliar</option></select></label><Field label="Duração" value="650ms" onChange={v=>send('style',{property:'animationDuration',value:v})}/><Field label="Atraso" value="0ms" onChange={v=>send('style',{property:'animationDelay',value:v})}/></ControlSection><ControlSection title="Responsivo" icon={<Maximize2/>}><div className="visibility-grid">{(['desktop','tablet','mobile'] as const).map(device=><label key={device}><span>{device==='desktop'?'Desktop':device==='tablet'?'Tablet':'Celular'}</span><select defaultValue="show" onChange={e=>visibility(device,e.target.value==='hide')}><option value="show">Visível</option><option value="hide">Oculto</option></select></label>)}</div></ControlSection><ControlSection title="Ações" icon={<ChevronsUpDown/>}><div className="action-list"><button onClick={()=>{const name=window.prompt('Nome do modelo:','Meu modelo');if(name)send('request-template',{name})}}><Copy/>Salvar como modelo</button><button onClick={()=>send('duplicate')}><Copy/>Duplicar elemento</button><button className="danger" onClick={()=>confirm?send('delete'):setConfirm(true)}><Trash2/>{confirm?'Confirmar exclusão':'Excluir elemento'}</button></div></ControlSection></>;
}
function ControlSection({title,icon,children}:{title:string;icon:React.ReactNode;children:React.ReactNode}){return <section className="control-section"><h3>{icon}{title}</h3><div>{children}</div></section>}
function Field({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label className="field"><span>{label}</span><input defaultValue={value} onBlur={e=>onChange(e.target.value)}/></label>}
function toHex(color:string){const nums=color?.match(/\d+/g);if(!nums||nums.length<3)return '#ffffff';return '#'+nums.slice(0,3).map(value=>Number(value).toString(16).padStart(2,'0')).join('')}
