import { AlignCenter, AlignLeft, AlignRight, ArrowDown, ArrowUp, ChevronsUpDown, Copy, EyeOff, Link2, Lock, Maximize2, Paintbrush, SlidersHorizontal, Trash2, Type } from 'lucide-react';
import { useState } from 'react';
import { useEditorStore } from '../stores/editorStore';
import { analyzeResponsiveness, applySafeResponsiveFixes, ensureAnimationRuntime, ensureAnimationStyles, setDeviceVisibility, setResponsiveStyle } from '../utils/responsive';
import { getActivePage } from '../stores/editorStore';
import { auditPage } from '../utils/audit';

export function Inspector() {
  const selected = useEditorStore((state)=>state.selected);
  const tab = useEditorStore((state)=>state.inspectorTab);
  const setTab = useEditorStore((state)=>state.setInspectorTab);
  const project = useEditorStore((state)=>state.project);
  const device = useEditorStore((state)=>state.device);
  const updatePage = useEditorStore((state)=>state.updatePage);
  const page=getActivePage(project);
  const issues=analyzeResponsiveness(page.html,page.css);
  const audit=auditPage(page);
  function send(type:string,payload:Record<string,string>={}) {
    if(type==='style'&&selected&&payload.property){updatePage({css:setResponsiveStyle(page.css,selected.id,payload.property,payload.value??'',device,project.settings.breakpoints)},`Estilo ${device}`);return}
    const frame=document.querySelector<HTMLIFrameElement>('.canvas-frame iframe');frame?.contentWindow?.postMessage({source:'webdev-editor',type,id:selected?.id,...payload},'*')
  }
  return <aside className="inspector"><div className="inspector-tabs"><button className={tab==='content'?'active':''} onClick={()=>setTab('content')}>Conteúdo</button><button className={tab==='style'?'active':''} onClick={()=>setTab('style')}>Estilo</button><button className={tab==='advanced'?'active':''} onClick={()=>setTab('advanced')}>Avançado</button></div>
    {!selected ? <div className="no-selection"><SlidersHorizontal/><h3>Nenhum elemento selecionado</h3><p>Clique elemento no canvas.</p>{issues.length?<div className="responsive-audit"><strong>{issues.length} ajustes responsivos</strong>{issues.slice(0,3).map(issue=><span key={issue.type+issue.message}>{issue.message}</span>)}<button onClick={()=>updatePage({css:applySafeResponsiveFixes(page.css)},'Corrigir responsividade')}>Aplicar correções seguras</button></div>:null}{audit.length?<div className="responsive-audit quality-audit"><strong>{audit.length} alertas de qualidade</strong>{audit.slice(0,5).map((issue,index)=><span key={`${issue.type}-${index}`}>{issue.message}</span>)}</div>:<div className="responsive-audit quality-audit"><strong>Auditoria aprovada</strong><span>SEO e acessibilidade básicos válidos.</span></div>}</div> : <div className="inspector-content"><div className="selected-heading"><span>&lt;{selected.tagName}&gt; · {device==='desktop'?'Desktop':device==='tablet'?'Tablet':'Celular'}</span><strong>{selected.className||selected.tagName}</strong></div>
    {tab==='content'?<ContentControls selected={selected} send={send} assets={project.files.filter(file=>file.type.startsWith('image')||/\.(png|jpe?g|gif|webp|svg)$/i.test(file.path))}/>:null}{tab==='style'?<StyleControls selected={selected} send={send}/>:null}{tab==='advanced'?<AdvancedControls selected={selected} send={send} pageHtml={page.html} pageCss={page.css} pageJavascript={page.javascript} updateCss={css=>updatePage({css},'Configurar movimento')} updateMotion={(html,css,javascript)=>updatePage({html,css,javascript},'Configurar movimento')} breakpoints={project.settings.breakpoints}/>:null}</div>}
  </aside>;
}

type Send=(type:string,payload?:Record<string,string>)=>void;
function ContentControls({selected,send,assets}:{selected:NonNullable<ReturnType<typeof useEditorStore.getState>['selected']>;send:Send;assets:{path:string;name:string}[]}) {
  return <><ControlSection title="Conteúdo" icon={<Type/>}>{selected.text!==''?<label className="field vertical"><span>Texto</span><textarea defaultValue={selected.text} onBlur={e=>send('content',{property:'text',value:e.target.value})}/></label>:null}{selected.tagName==='img'?<><label className="field vertical"><span>Imagem</span><select defaultValue={selected.attributes.src??''} onChange={e=>send('content',{property:'src',value:e.target.value})}><option value={selected.attributes.src??''}>Imagem atual</option>{assets.map(asset=><option key={asset.path} value={asset.path}>{asset.name}</option>)}</select></label><label className="field vertical"><span>Texto alternativo</span><input defaultValue={selected.attributes.alt??''} onBlur={e=>send('content',{property:'alt',value:e.target.value})}/></label></>:null}<label className="field vertical"><span>Classes CSS</span><input defaultValue={selected.className} onBlur={e=>send('content',{property:'className',value:e.target.value})}/></label>{selected.tagName==='a'?<label className="field vertical"><span>Link</span><input defaultValue={selected.attributes.href??''} placeholder="https://" onBlur={e=>send('content',{property:'href',value:e.target.value})}/></label>:null}</ControlSection></>;
}
function StyleControls({selected,send}:{selected:NonNullable<ReturnType<typeof useEditorStore.getState>['selected']>;send:Send}) {
  const s=selected.styles;
  const value=(key:string)=>s[key]??'';
  return <><ControlSection title="Dimensões" icon={<Maximize2/>}><label className="field vertical"><span>Exibição</span><select defaultValue={value('display')} onChange={e=>send('style',{property:'display',value:e.target.value})}><option>block</option><option>flex</option><option>grid</option><option>inline-flex</option><option>inline-block</option><option>none</option></select></label><div className="two-fields"><Field label="Largura" value={value('width')} onChange={v=>send('style',{property:'width',value:v})}/><Field label="Altura" value={value('height')} onChange={v=>send('style',{property:'height',value:v})}/><Field label="Mín. largura" value={value('minWidth')} onChange={v=>send('style',{property:'minWidth',value:v})}/><Field label="Máx. largura" value={value('maxWidth')} onChange={v=>send('style',{property:'maxWidth',value:v})}/><Field label="Mín. altura" value={value('minHeight')} onChange={v=>send('style',{property:'minHeight',value:v})}/><Field label="Máx. altura" value={value('maxHeight')} onChange={v=>send('style',{property:'maxHeight',value:v})}/></div><Field label="Proporção" value={value('aspectRatio')||'auto'} onChange={v=>send('style',{property:'aspectRatio',value:v})}/><Field label="Margem" value={value('margin')} onChange={v=>send('style',{property:'margin',value:v})}/><Field label="Preenchimento" value={value('padding')} onChange={v=>send('style',{property:'padding',value:v})}/></ControlSection>
  <ControlSection title="Flexível" icon={<ChevronsUpDown/>}><div className="two-fields"><SelectField label="Direção" value={value('flexDirection')||'row'} options={['row','column','row-reverse','column-reverse']} onChange={v=>send('style',{property:'flexDirection',value:v})}/><SelectField label="Quebra" value={value('flexWrap')||'nowrap'} options={['nowrap','wrap','wrap-reverse']} onChange={v=>send('style',{property:'flexWrap',value:v})}/><SelectField label="Distribuir" value={value('justifyContent')||'flex-start'} options={['flex-start','center','flex-end','space-between','space-around','space-evenly']} onChange={v=>send('style',{property:'justifyContent',value:v})}/><SelectField label="Alinhar" value={value('alignItems')||'stretch'} options={['stretch','flex-start','center','flex-end','baseline']} onChange={v=>send('style',{property:'alignItems',value:v})}/></div><div className="two-fields"><Field label="Espaço" value={value('gap')||'0px'} onChange={v=>send('style',{property:'gap',value:v})}/><Field label="Ordem" value={value('order')||'0'} onChange={v=>send('style',{property:'order',value:v})}/></div></ControlSection>
  <ControlSection title="Grade" icon={<Maximize2/>}><Field label="Colunas" value={value('gridTemplateColumns')||'repeat(2, 1fr)'} onChange={v=>send('style',{property:'gridTemplateColumns',value:v})}/><Field label="Linha/coluna" value={value('gridColumn')||'auto'} onChange={v=>send('style',{property:'gridColumn',value:v})}/><Field label="Espaço" value={value('gap')||'0px'} onChange={v=>send('style',{property:'gap',value:v})}/></ControlSection>
  <ControlSection title="Tipografia" icon={<Type/>}><div className="two-fields"><Field label="Tamanho" value={value('fontSize')} onChange={v=>send('style',{property:'fontSize',value:v})}/><Field label="Peso" value={value('fontWeight')} onChange={v=>send('style',{property:'fontWeight',value:v})}/></div><label className="color-field"><span>Cor</span><input type="color" defaultValue={toHex(value('color'))} onChange={e=>send('style',{property:'color',value:e.target.value})}/><code>{toHex(value('color'))}</code></label><button className="tiny-action fluid-action" onClick={()=>send('style',{property:'fontSize',value:'clamp(1rem, 2.5vw, 3rem)'})}>Aplicar tamanho fluido</button></ControlSection>
  <ControlSection title="Aparência" icon={<Paintbrush/>}><label className="color-field"><span>Fundo</span><input type="color" defaultValue={toHex(value('backgroundColor'))} onChange={e=>send('style',{property:'backgroundColor',value:e.target.value})}/><code>{toHex(value('backgroundColor'))}</code></label><Field label="Borda" value={value('border')||'0 solid transparent'} onChange={v=>send('style',{property:'border',value:v})}/><Field label="Arredondamento" value={value('borderRadius')} onChange={v=>send('style',{property:'borderRadius',value:v})}/><Field label="Sombra" value={value('boxShadow')||'none'} onChange={v=>send('style',{property:'boxShadow',value:v})}/><Field label="Opacidade" value={value('opacity')||'1'} onChange={v=>send('style',{property:'opacity',value:v})}/></ControlSection>
  <ControlSection title="Posicionamento" icon={<Maximize2/>}><SelectField label="Posição" value={value('position')||'static'} options={['static','relative','absolute','fixed','sticky']} onChange={v=>send('style',{property:'position',value:v})}/><div className="two-fields"><Field label="Topo" value={value('top')||'auto'} onChange={v=>send('style',{property:'top',value:v})}/><Field label="Direita" value={value('right')||'auto'} onChange={v=>send('style',{property:'right',value:v})}/><Field label="Base" value={value('bottom')||'auto'} onChange={v=>send('style',{property:'bottom',value:v})}/><Field label="Esquerda" value={value('left')||'auto'} onChange={v=>send('style',{property:'left',value:v})}/><Field label="Camada Z" value={value('zIndex')||'auto'} onChange={v=>send('style',{property:'zIndex',value:v})}/><Field label="Overflow" value={value('overflow')||'visible'} onChange={v=>send('style',{property:'overflow',value:v})}/></div></ControlSection></>;
}
function AdvancedControls({selected,send,pageHtml,pageCss,pageJavascript,updateCss,updateMotion,breakpoints}:{selected:NonNullable<ReturnType<typeof useEditorStore.getState>['selected']>;send:Send;pageHtml:string;pageCss:string;pageJavascript:string;updateCss:(css:string)=>void;updateMotion:(html:string,css:string,javascript:string)=>void;breakpoints:{mobile:number;tablet:number;desktop:number}}) {
  const [confirm,setConfirm]=useState(false);
  function motion(property:string,value:string){const doc=new DOMParser().parseFromString(pageHtml,'text/html');const element=doc.querySelector(`[data-wd-id="${CSS.escape(selected.id)}"]`);if(!element)return;if(value)element.setAttribute(property,value);else element.removeAttribute(property);updateMotion(doc.body.innerHTML,value?ensureAnimationStyles(pageCss):pageCss,value?ensureAnimationRuntime(pageJavascript):pageJavascript)}
  function visibility(device:'desktop'|'tablet'|'mobile',hidden:boolean){updateCss(setDeviceVisibility(pageCss,selected.id,device,hidden,breakpoints))}
  return <>
    <ControlSection title="Identidade" icon={<Link2/>}><label className="field vertical"><span>ID editorial</span><input value={selected.id} readOnly/></label><label className="field vertical"><span>Classe CSS</span><input defaultValue={selected.className} onBlur={e=>send('content',{property:'className',value:e.target.value})}/></label></ControlSection>
    <ControlSection title="Animação" icon={<ChevronsUpDown/>}><SelectField label="Entrada" value={selected.attributes['data-wd-animation']||''} options={['','fade-up','fade-down','fade-left','fade-right','fade-in','zoom-in','rotate-in','flip-in','bounce','blur-in']} onChange={v=>motion('data-wd-animation',v)}/><div className="two-fields"><Field label="Duração" value="0.7s" onChange={v=>send('style',{property:'--wd-duration',value:v})}/><Field label="Atraso" value="0s" onChange={v=>send('style',{property:'--wd-delay',value:v})}/></div><SelectField label="Curva" value="ease" options={['ease','linear','ease-in','ease-out','ease-in-out','cubic-bezier(.2,.8,.2,1)']} onChange={v=>send('style',{property:'--wd-easing',value:v})}/><SelectField label="Repetir ao rolar" value={selected.attributes['data-wd-repeat']||'false'} options={['false','true']} onChange={v=>motion('data-wd-repeat',v)}/><SelectField label="Ao passar mouse" value={selected.attributes['data-wd-hover']||''} options={['','grow','lift']} onChange={v=>motion('data-wd-hover',v)}/><SelectField label="Loop" value={selected.attributes['data-wd-loop']||''} options={['','pulse','float']} onChange={v=>motion('data-wd-loop',v)}/></ControlSection>
    <ControlSection title="Efeitos de movimento" icon={<ChevronsUpDown/>}><Field label="Parallax" value={selected.attributes['data-wd-parallax']||'0'} onChange={v=>motion('data-wd-parallax',v)}/><SelectField label="Seguir mouse" value={selected.attributes['data-wd-mouse']||'false'} options={['false','true']} onChange={v=>motion('data-wd-mouse',v)}/><Field label="Escalonar filhos" value={selected.attributes['data-wd-stagger']||'0'} onChange={v=>motion('data-wd-stagger',v)}/><button className="tiny-action fluid-action" onClick={()=>send('style',{property:'position',value:'sticky'})}>Ativar posição fixa</button></ControlSection>
    <ControlSection title="Transformação" icon={<Maximize2/>}><div className="two-fields"><Field label="Mover X" value="0px" onChange={v=>send('style',{property:'translate',value:`${v} 0`})}/><Field label="Mover Y" value="0px" onChange={v=>send('style',{property:'translate',value:`0 ${v}`})}/><Field label="Girar" value="0deg" onChange={v=>send('style',{property:'rotate',value:v})}/><Field label="Escala" value="1" onChange={v=>send('style',{property:'scale',value:v})}/></div></ControlSection>
    <ControlSection title="Responsivo" icon={<Maximize2/>}><div className="visibility-grid">{(['desktop','tablet','mobile'] as const).map(device=><label key={device}><span>{device==='desktop'?'Desktop':device==='tablet'?'Tablet':'Celular'}</span><select defaultValue="show" onChange={e=>visibility(device,e.target.value==='hide')}><option value="show">Visível</option><option value="hide">Oculto</option></select></label>)}</div></ControlSection>
    <ControlSection title="Organização" icon={<ChevronsUpDown/>}><div className="action-grid"><button onClick={()=>send('up')}><ArrowUp/>Subir</button><button onClick={()=>send('down')}><ArrowDown/>Descer</button><button onClick={()=>send('lock')}><Lock/>Bloquear</button><button onClick={()=>send('hide')}><EyeOff/>Ocultar</button></div></ControlSection>
    <ControlSection title="Alinhamento múltiplo" icon={<AlignCenter/>}><div className="action-grid"><button onClick={()=>send('align-left')}><AlignLeft/>Esquerda</button><button onClick={()=>send('align-center')}><AlignCenter/>Centro</button><button onClick={()=>send('align-right')}><AlignRight/>Direita</button><button onClick={()=>send('distribute')}><ChevronsUpDown/>Distribuir</button></div></ControlSection>
    <ControlSection title="Ações" icon={<ChevronsUpDown/>}><div className="action-list"><button onClick={()=>{const name=window.prompt('Nome do modelo:','Meu modelo');if(name)send('request-template',{name})}}><Copy/>Salvar como modelo</button><button onClick={()=>send('copy')}><Copy/>Copiar elemento</button><button onClick={()=>send('duplicate')}><Copy/>Duplicar elemento</button><button className="danger" onClick={()=>confirm?send('delete'):setConfirm(true)}><Trash2/>{confirm?'Confirmar exclusão':'Excluir elemento'}</button></div></ControlSection>
  </>;
}
function ControlSection({title,icon,children}:{title:string;icon:React.ReactNode;children:React.ReactNode}){return <section className="control-section"><h3>{icon}{title}</h3><div>{children}</div></section>}
function Field({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label className="field"><span>{label}</span><input defaultValue={value} onBlur={e=>onChange(e.target.value)}/></label>}
function SelectField({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(value:string)=>void}){return <label className="field vertical"><span>{label}</span><select value={value} onChange={event=>onChange(event.target.value)}>{options.map(option=><option key={option} value={option}>{option||'Nenhuma'}</option>)}</select></label>}
function toHex(color:string){const nums=color?.match(/\d+/g);if(!nums||nums.length<3)return '#ffffff';return '#'+nums.slice(0,3).map(value=>Number(value).toString(16).padStart(2,'0')).join('')}
