import { X } from 'lucide-react';
import { useState } from 'react';
import { getActivePage, useEditorStore } from '../stores/editorStore';

export function PageSettingsModal({onClose}:{onClose:()=>void}){
  const project=useEditorStore(state=>state.project);const page=getActivePage(project);
  const updatePage=useEditorStore(state=>state.updatePage);const duplicatePage=useEditorStore(state=>state.duplicatePage);const deletePage=useEditorStore(state=>state.deletePage);
  const [form,setForm]=useState({name:page.name,path:page.path,title:page.seo?.title??page.name,description:page.seo?.description??'',keywords:page.seo?.keywords??'',canonical:page.seo?.canonical??'',ogImage:page.seo?.ogImage??'',noindex:page.seo?.noindex??false,headCode:page.headCode??''});
  function save(){updatePage({name:form.name,path:form.path,headCode:form.headCode,seo:{title:form.title,description:form.description,keywords:form.keywords,canonical:form.canonical,ogImage:form.ogImage,noindex:form.noindex}},'Configurar página');onClose()}
  return <div className="modal-backdrop"><section className="settings-modal page-settings"><header><div><h2>Página e SEO</h2><p>Metadados exportados no HTML.</p></div><button className="icon-button" onClick={onClose}><X/></button></header><div className="settings-body"><fieldset><legend>Arquivo</legend><div className="two-fields"><ModalField label="Nome" value={form.name} change={name=>setForm({...form,name})}/><ModalField label="Caminho" value={form.path} change={path=>setForm({...form,path})}/></div></fieldset><fieldset><legend>SEO</legend><ModalField label="Título" value={form.title} change={title=>setForm({...form,title})}/><label className="field vertical"><span>Descrição</span><textarea value={form.description} onChange={event=>setForm({...form,description:event.target.value})}/></label><ModalField label="Palavras-chave" value={form.keywords} change={keywords=>setForm({...form,keywords})}/><ModalField label="URL canônica" value={form.canonical} change={canonical=>setForm({...form,canonical})}/><ModalField label="Imagem social" value={form.ogImage} change={ogImage=>setForm({...form,ogImage})}/><label className="toggle-row"><span><strong>Não indexar</strong><small>Adiciona robots noindex.</small></span><input type="checkbox" checked={form.noindex} onChange={event=>setForm({...form,noindex:event.target.checked})}/></label></fieldset><fieldset><legend>Código no cabeçalho</legend><label className="field vertical"><span>HTML personalizado</span><textarea value={form.headCode} onChange={event=>setForm({...form,headCode:event.target.value})}/></label></fieldset></div><footer><button className="button subtle" onClick={()=>{duplicatePage(page.id);onClose()}}>Duplicar</button><button className="button danger-button" disabled={project.pages.length===1} onClick={()=>{deletePage(page.id);onClose()}}>Excluir</button><button className="button primary" onClick={save}>Salvar</button></footer></section></div>
}
function ModalField({label,value,change}:{label:string;value:string;change:(value:string)=>void}){return <label className="field vertical"><span>{label}</span><input value={value} onChange={event=>change(event.target.value)}/></label>}
