import { X } from 'lucide-react';
import { useState } from 'react';
import { useEditorStore } from '../stores/editorStore';

export function SettingsModal({onClose}:{onClose:()=>void}) {
  const project=useEditorStore(state=>state.project);
  const updateSettings=useEditorStore(state=>state.updateSettings);
  const [breakpoints,setBreakpoints]=useState(project.settings.breakpoints);
  function save(){updateSettings({breakpoints});onClose()}
  return <div className="modal-backdrop" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section className="settings-modal"><header><div><h2>Configurações do projeto</h2><p>Preferências locais e responsivas.</p></div><button className="icon-button" onClick={onClose}><X/></button></header><div className="settings-body"><fieldset><legend>Execução</legend><label className="toggle-row"><span><strong>Executar JavaScript</strong><small>Ativa scripts no canvas e preview.</small></span><input type="checkbox" checked={project.settings.executeScripts} onChange={event=>updateSettings({executeScripts:event.target.checked})}/></label><label className="toggle-row"><span><strong>Correção responsiva</strong><small>Analisa overflow automaticamente.</small></span><input type="checkbox" checked={project.settings.autoResponsive} onChange={event=>updateSettings({autoResponsive:event.target.checked})}/></label></fieldset><fieldset><legend>Breakpoints</legend><div className="breakpoint-grid"><label>Celular<input type="number" value={breakpoints.mobile} onChange={event=>setBreakpoints({...breakpoints,mobile:Number(event.target.value)})}/><span>px</span></label><label>Tablet<input type="number" value={breakpoints.tablet} onChange={event=>setBreakpoints({...breakpoints,tablet:Number(event.target.value)})}/><span>px</span></label><label>Desktop<input type="number" value={breakpoints.desktop} onChange={event=>setBreakpoints({...breakpoints,desktop:Number(event.target.value)})}/><span>px</span></label></div></fieldset><fieldset><legend>Armazenamento</legend><p className="settings-note">Projetos usam IndexedDB do navegador. Exporte backup antes de limpar dados locais.</p><div className="capability-row"><span>API de diretórios</span><strong className={'showDirectoryPicker' in window?'available':'fallback'}>{'showDirectoryPicker' in window?'Disponível':'ZIP alternativo'}</strong></div></fieldset></div><footer><button className="button subtle" onClick={onClose}>Cancelar</button><button className="button primary" onClick={save}>Salvar configurações</button></footer></section></div>;
}
