import { X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useEditorStore } from '../stores/editorStore';

export function SettingsModal({onClose}:{onClose:()=>void}) {
  const project=useEditorStore(state=>state.project);const updateSettings=useEditorStore(state=>state.updateSettings);
  const [breakpoints,setBreakpoints]=useState(project.settings.breakpoints);const [faviconPath,setFaviconPath]=useState(project.settings.faviconPath??'');const [globalHeadCode,setGlobalHeadCode]=useState(project.settings.globalHeadCode??'');
  const [storage,setStorage]=useState<{usage:number;quota:number}|null>(null);
  useEffect(()=>{void navigator.storage?.estimate().then(estimate=>setStorage({usage:estimate.usage??0,quota:estimate.quota??0}))},[]);
  function save(){updateSettings({breakpoints,faviconPath,globalHeadCode});onClose()}
  return <div className="modal-backdrop" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section className="settings-modal"><header><div><h2>Configurações do projeto</h2><p>Preferências locais e responsivas.</p></div><button className="icon-button" onClick={onClose}><X/></button></header><div className="settings-body">
    <fieldset><legend>Execução</legend><label className="toggle-row"><span><strong>Executar JavaScript</strong><small>Ativa scripts no canvas e preview.</small></span><input type="checkbox" checked={project.settings.executeScripts} onChange={event=>updateSettings({executeScripts:event.target.checked})}/></label><label className="toggle-row"><span><strong>Correção responsiva</strong><small>Analisa overflow automaticamente.</small></span><input type="checkbox" checked={project.settings.autoResponsive} onChange={event=>updateSettings({autoResponsive:event.target.checked})}/></label></fieldset>
    <fieldset><legend>Breakpoints</legend><div className="breakpoint-grid"><label>Celular<input type="number" value={breakpoints.mobile} onChange={event=>setBreakpoints({...breakpoints,mobile:Number(event.target.value)})}/><span>px</span></label><label>Tablet<input type="number" value={breakpoints.tablet} onChange={event=>setBreakpoints({...breakpoints,tablet:Number(event.target.value)})}/><span>px</span></label><label>Desktop<input type="number" value={breakpoints.desktop} onChange={event=>setBreakpoints({...breakpoints,desktop:Number(event.target.value)})}/><span>px</span></label></div></fieldset>
    <fieldset><legend>Cabeçalho global</legend><label className="field vertical"><span>Caminho do favicon</span><input value={faviconPath} onChange={event=>setFaviconPath(event.target.value)} placeholder="assets/favicon.png"/></label><label className="field vertical"><span>Código em todas páginas</span><textarea value={globalHeadCode} onChange={event=>setGlobalHeadCode(event.target.value)} placeholder="Meta tags, fontes ou scripts"/></label></fieldset>
    <fieldset><legend>Armazenamento</legend><p className="settings-note">Projetos usam IndexedDB e OPFS. Exporte backup antes de limpar dados locais.</p><div className="capability-row"><span>API de diretórios</span><strong className={'showDirectoryPicker' in window?'available':'fallback'}>{'showDirectoryPicker' in window?'Disponível':'ZIP alternativo'}</strong></div><div className="capability-row storage-usage"><span>Espaço local</span><strong>{storage?`${formatBytes(storage.usage)} / ${formatBytes(storage.quota)}`:'Calculando'}</strong></div></fieldset>
  </div><footer><button className="button subtle" onClick={onClose}>Cancelar</button><button className="button primary" onClick={save}>Salvar configurações</button></footer></section></div>;
}

function formatBytes(value:number){if(!value)return '0 B';const units=['B','KB','MB','GB','TB'];const index=Math.min(Math.floor(Math.log(value)/Math.log(1024)),units.length-1);return `${(value/1024**index).toFixed(index>1?1:0)} ${units[index]}`}
