import { Box, ChartNoAxesColumn, ChevronDown, Columns3, GalleryHorizontal, Heading1, Image, LayoutGrid, List, Mail, MapPin, Menu, MessageSquareQuote, MousePointerClick, PanelTop, PlaySquare, Search as SearchIcon, SeparatorHorizontal, Share2, Space, Text, type LucideIcon } from 'lucide-react';

export interface Widget { id: string; name: string; icon: LucideIcon; html: string }
export const widgetGroups: { name: string; items: Widget[] }[] = [
  { name: 'Layout', items: [
    { id: 'container', name: 'Container', icon: Box, html: '<section data-wd-name="Container" style="padding:60px 24px"><div style="max-width:1180px;margin:auto"><h2>Novo container</h2><p>Adicione conteúdo aqui.</p></div></section>' },
    { id: 'grid', name: 'Grade', icon: LayoutGrid, html: '<div data-wd-name="Grade" style="display:grid;grid-template-columns:repeat(3,1fr);gap:24px;padding:24px"><div>Coluna 1</div><div>Coluna 2</div><div>Coluna 3</div></div>' },
    { id: 'columns', name: 'Colunas', icon: Columns3, html: '<div data-wd-name="Colunas" style="display:flex;gap:24px;padding:24px"><div style="flex:1">Coluna 1</div><div style="flex:1">Coluna 2</div></div>' },
  ]},
  { name: 'Básicos', items: [
    { id: 'heading', name: 'Título', icon: Heading1, html: '<h2>Novo título</h2>' },
    { id: 'text', name: 'Texto', icon: Text, html: '<p>Escreva seu conteúdo aqui.</p>' },
    { id: 'button', name: 'Botão', icon: MousePointerClick, html: '<a href="#" class="button">Clique aqui</a>' },
    { id: 'list', name: 'Lista', icon: List, html: '<ul><li>Primeiro item</li><li>Segundo item</li><li>Terceiro item</li></ul>' },
    { id: 'separator', name: 'Separador', icon: SeparatorHorizontal, html: '<hr style="border:0;border-top:1px solid #d8dee8;margin:24px 0">' },
    { id: 'spacer', name: 'Espaçador', icon: Space, html: '<div data-wd-name="Espaçador" style="height:48px"></div>' },
  ]},
  { name: 'Mídia', items: [
    { id: 'image', name: 'Imagem', icon: Image, html: '<img alt="Imagem" src="https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=1200&q=80">' },
    { id: 'video', name: 'Vídeo', icon: PlaySquare, html: '<div style="aspect-ratio:16/9;background:#111827;color:#fff;display:grid;place-items:center">Vídeo</div>' },
    { id: 'gallery', name: 'Galeria', icon: GalleryHorizontal, html: '<div data-wd-name="Galeria" style="display:grid;grid-template-columns:repeat(3,1fr);gap:12px"><img alt="Galeria 1" src="https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=600&q=80"><img alt="Galeria 2" src="https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=600&q=80"><img alt="Galeria 3" src="https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=600&q=80"></div>' },
  ]},
  { name: 'Interativos', items: [
    { id: 'form', name: 'Formulário', icon: Mail, html: '<form data-wd-name="Formulário" style="display:grid;gap:12px;max-width:560px"><label>Nome<input required name="nome" style="display:block;width:100%;padding:12px;margin-top:6px"></label><label>E-mail<input required type="email" name="email" style="display:block;width:100%;padding:12px;margin-top:6px"></label><label>Mensagem<textarea name="mensagem" style="display:block;width:100%;padding:12px;margin-top:6px;min-height:120px"></textarea></label><button class="button" type="submit">Enviar mensagem</button></form>' },
    { id: 'accordion', name: 'Acordeão', icon: ChevronDown, html: '<div data-wd-name="Acordeão"><details open style="border-bottom:1px solid #ddd;padding:16px 0"><summary style="font-weight:700;cursor:pointer">Pergunta frequente</summary><p>Resposta detalhada para seus visitantes.</p></details><details style="border-bottom:1px solid #ddd;padding:16px 0"><summary style="font-weight:700;cursor:pointer">Outra pergunta</summary><p>Outra resposta importante.</p></details></div>' },
    { id: 'tabs', name: 'Abas', icon: PanelTop, html: '<div data-wd-name="Abas"><div style="display:flex;gap:8px;border-bottom:1px solid #ddd"><button style="padding:10px 16px;border:0;border-bottom:2px solid #3563ff;background:none">Visão geral</button><button style="padding:10px 16px;border:0;background:none">Detalhes</button></div><div style="padding:20px 0"><h3>Conteúdo da aba</h3><p>Organize informações em áreas compactas.</p></div></div>' },
    { id: 'menu', name: 'Menu', icon: Menu, html: '<nav data-wd-name="Menu" style="display:flex;gap:24px;align-items:center"><a href="#inicio">Início</a><a href="#servicos">Serviços</a><a href="#sobre">Sobre</a><a href="#contato">Contato</a></nav>' },
    { id: 'mobile-menu', name: 'Menu móvel', icon: Menu, html: '<details data-wd-name="Menu móvel" style="position:relative"><summary style="cursor:pointer;font-weight:700">☰ Menu</summary><nav style="position:absolute;z-index:20;right:0;display:grid;gap:12px;min-width:210px;padding:18px;background:white;box-shadow:0 12px 30px #0002"><a href="#inicio">Início</a><a href="#servicos">Serviços</a><a href="#contato">Contato</a></nav></details>' },
    { id: 'functional-tabs', name: 'Abas funcionais', icon: PanelTop, html: '<div data-wd-name="Abas funcionais"><input hidden checked type="radio" name="wd-tabs" id="wd-tab-1"><input hidden type="radio" name="wd-tabs" id="wd-tab-2"><div style="display:flex;gap:8px"><label for="wd-tab-1" style="padding:10px;cursor:pointer">Visão geral</label><label for="wd-tab-2" style="padding:10px;cursor:pointer">Detalhes</label></div><div style="padding:18px;border-top:1px solid #ddd">Conteúdo editável das abas.</div></div>' },
    { id: 'carousel', name: 'Carrossel', icon: GalleryHorizontal, html: '<div data-wd-name="Carrossel" style="display:flex;overflow-x:auto;scroll-snap-type:x mandatory;gap:16px"><article style="flex:0 0 80%;scroll-snap-align:center;padding:40px;background:#eef2ff">Slide 1</article><article style="flex:0 0 80%;scroll-snap-align:center;padding:40px;background:#e0f2fe">Slide 2</article><article style="flex:0 0 80%;scroll-snap-align:center;padding:40px;background:#fef3c7">Slide 3</article></div>' },
    { id: 'modal', name: 'Popup', icon: PanelTop, html: '<div data-wd-name="Popup"><button class="button" onclick="this.nextElementSibling.showModal()">Abrir popup</button><dialog style="max-width:560px;border:0;border-radius:12px;padding:32px;box-shadow:0 20px 60px #0005"><button onclick="this.parentElement.close()" style="float:right">✕</button><h2>Mensagem importante</h2><p>Edite conteúdo deste popup.</p></dialog></div>' },
    { id: 'search', name: 'Busca', icon: SearchIcon, html: '<form role="search" data-wd-name="Busca" style="display:flex;gap:8px"><input type="search" placeholder="Buscar..." style="flex:1;padding:12px"><button class="button">Buscar</button></form>' },
  ]},
  { name: 'Avançados', items: [
    { id: 'testimonial', name: 'Depoimento', icon: MessageSquareQuote, html: '<figure data-wd-name="Depoimento" style="margin:0;padding:28px;border:1px solid #e2e8f0;border-radius:10px"><blockquote style="font-size:20px;margin:0 0 20px">“Excelente resultado e processo muito claro.”</blockquote><figcaption><strong>Nome do cliente</strong><br><small>Empresa</small></figcaption></figure>' },
    { id: 'counter', name: 'Contador', icon: ChartNoAxesColumn, html: '<div data-wd-name="Contador" style="text-align:center"><strong style="font-size:48px;color:#3563ff">250+</strong><p>Projetos entregues</p></div>' },
    { id: 'progress', name: 'Progresso', icon: ChartNoAxesColumn, html: '<div data-wd-name="Progresso"><div style="display:flex;justify-content:space-between"><strong>Desempenho</strong><span>85%</span></div><div style="height:8px;background:#e2e8f0;border-radius:4px;margin-top:8px"><div style="height:100%;width:85%;background:#3563ff;border-radius:4px"></div></div></div>' },
    { id: 'social', name: 'Redes sociais', icon: Share2, html: '<div data-wd-name="Redes sociais" style="display:flex;gap:10px"><a href="#" aria-label="Instagram" style="padding:10px;border:1px solid #ddd;border-radius:50%">IG</a><a href="#" aria-label="LinkedIn" style="padding:10px;border:1px solid #ddd;border-radius:50%">IN</a><a href="#" aria-label="YouTube" style="padding:10px;border:1px solid #ddd;border-radius:50%">YT</a></div>' },
    { id: 'map', name: 'Mapa', icon: MapPin, html: '<div data-wd-name="Mapa" style="min-height:320px;background:#e8edf3;display:grid;place-items:center;border-radius:8px"><div style="text-align:center"><strong>Mapa</strong><p>Insira código incorporado.</p></div></div>' },
    { id: 'pricing', name: 'Preços', icon: ChartNoAxesColumn, html: '<section data-wd-name="Preços" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:20px"><article style="padding:28px;border:1px solid #ddd;border-radius:12px"><h3>Básico</h3><strong style="font-size:40px">R$ 99</strong><p>Recurso essencial<br>Suporte padrão</p><a class="button" href="#">Escolher</a></article><article style="padding:28px;border:2px solid #3563ff;border-radius:12px"><h3>Profissional</h3><strong style="font-size:40px">R$ 199</strong><p>Todos recursos<br>Suporte prioritário</p><a class="button" href="#">Escolher</a></article></section>' },
    { id: 'table', name: 'Tabela', icon: List, html: '<div data-wd-name="Tabela" style="overflow-x:auto"><table style="width:100%;border-collapse:collapse"><thead><tr><th style="padding:12px;text-align:left;border-bottom:2px solid #ddd">Plano</th><th style="padding:12px;text-align:left;border-bottom:2px solid #ddd">Valor</th></tr></thead><tbody><tr><td style="padding:12px;border-bottom:1px solid #eee">Básico</td><td style="padding:12px;border-bottom:1px solid #eee">R$ 99</td></tr></tbody></table></div>' },
    { id: 'breadcrumb', name: 'Navegação', icon: ChevronDown, html: '<nav aria-label="Navegação estrutural" data-wd-name="Breadcrumb"><a href="/">Início</a> <span aria-hidden="true">/</span> <a href="#">Categoria</a> <span aria-hidden="true">/</span> <span>Página</span></nav>' },
    { id: 'logo', name: 'Logotipo', icon: Image, html: '<a href="/" data-wd-name="Logotipo" aria-label="Página inicial" style="display:inline-flex;align-items:center;gap:10px;font-size:24px;font-weight:800"><span style="width:36px;height:36px;background:#3563ff;border-radius:8px"></span>Sua marca</a>' },
    { id: 'hotspot', name: 'Ponto interativo', icon: MapPin, html: '<figure data-wd-name="Hotspot" style="position:relative;margin:0"><img alt="Imagem interativa" src="https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80"><button aria-label="Ver detalhe" title="Detalhe editável" style="position:absolute;left:55%;top:40%;width:34px;height:34px;border:4px solid white;border-radius:50%;background:#3563ff;color:white">+</button></figure>' },
    { id: 'shape-divider', name: 'Divisor curvo', icon: SeparatorHorizontal, html: '<svg data-wd-name="Divisor curvo" viewBox="0 0 1200 120" preserveAspectRatio="none" style="display:block;width:100%;height:80px" aria-hidden="true"><path d="M0,80 C300,140 900,0 1200,60 L1200,120 L0,120 Z" fill="#3563ff"/></svg>' },
    { id: 'embed', name: 'Incorporar', icon: PlaySquare, html: '<iframe data-wd-name="Incorporar" title="Conteúdo incorporado" loading="lazy" src="about:blank" style="width:100%;min-height:360px;border:1px solid #ddd"></iframe>' },
    { id: 'lottie', name: 'Lottie', icon: PlaySquare, html: '<iframe data-wd-name="Lottie" title="Animação Lottie" loading="lazy" src="https://lottie.host/embed/" style="width:100%;min-height:320px;border:0"></iframe>' },
    { id: 'lightbox', name: 'Lightbox', icon: Image, html: '<a data-wd-name="Lightbox" href="https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1600&q=90" target="_blank"><img alt="Abrir imagem ampliada" src="https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=700&q=80"></a>' },
    { id: 'countdown', name: 'Contagem regressiva', icon: ChartNoAxesColumn, html: '<div data-wd-name="Contagem regressiva" data-wd-countdown="2030-01-01T00:00:00" style="display:flex;gap:12px;text-align:center"><strong style="padding:18px;background:#111827;color:white;border-radius:8px">00<br><small>DIAS</small></strong><strong style="padding:18px;background:#111827;color:white;border-radius:8px">00<br><small>HORAS</small></strong><strong style="padding:18px;background:#111827;color:white;border-radius:8px">00<br><small>MIN</small></strong></div>' },
  ]},
];
